steps:
  #コンテナイメージをビルドする
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t=gcr.io/$PROJECT_ID/harumax-identity-service', '.']
    # env:
    #   - "_HTML_NAME=$_HTML_NAME"
    #   - "_BASE_DOMAIN=$_BASE_DOMAIN"
    #   - "_FIREBASE_API_KEY=$_FIREBASE_API_KEY"
    #   - "_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN"
    #   - "_FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL"
    #   - "_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID"
    #   - "_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET"
    #   - "_FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID"
    #   - "_FIREBASE_APP_ID=$_FIREBASE_APP_ID"
    #   - "_FIREBASE_MESUREMENT_ID=$_FIREBASE_MESUREMENT_ID"
    #   - "_IDENTITY_SERVICE_URL=$_IDENTITY_SERVICE_URL"
  #コンテナイメージをpushする
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/harumax-identity-service"]
  #もろもろの設定
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "alpha"
      - "run"
      - "deploy"
      - "harumax-identity-service"
      - "--image=gcr.io/$PROJECT_ID/harumax-identity-service"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
  substitutions:
    - _HTML_NAME=""$_HTML_NAME"
    - _BASE_DOMAIN="$_BASE_DOMAIN"
    - _FIREBASE_API_KEY="$_FIREBASE_API_KEY"
    - _FIREBASE_AUTH_DOMAIN="$_FIREBASE_AUTH_DOMAIN"
    - _FIREBASE_DATABASE_URL="$_FIREBASE_DATABASE_URL"
    - _FIREBASE_PROJECT_ID="$_FIREBASE_PROJECT_ID"
    - _FIREBASE_STORAGE_BUCKET="$_FIREBASE_STORAGE_BUCKET"
    - _FIREBASE_MESSAGING_SENDER_ID="$_FIREBASE_MESSAGING_SENDER_ID"
    - _FIREBASE_APP_ID="$_FIREBASE_APP_ID"
    - _FIREBASE_MESUREMENT_ID="$_FIREBASE_MESUREMENT_ID"
    - _IDENTITY_SERVICE_URL="$_IDENTITY_SERVICE_URL"
