options:
  env:
    - "HTML_NAME"="$_HTML_NAME"
    - "BASE_DOMAIN"="$_BASE_DOMAIN"
    - "FIREBASE_API_KEY"="$_FIREBASE_API_KEY"
    - "FIREBASE_AUTH_DOMAIN"="$_FIREBASE_AUTH_DOMAIN"
    - "FIREBASE_DATABASE_URL"="$_FIREBASE_DATABASE_URL"
    - "FIREBASE_PROJECT_ID"="$_FIREBASE_PROJECT_ID"
    - "FIREBASE_STORAGE_BUCKET"="$_FIREBASE_STORAGE_BUCKET"
    - "FIREBASE_MESSAGING_SENDER_ID"="$_FIREBASE_MESSAGING_SENDER_ID"
    - "FIREBASE_APP_ID"="$_FIREBASE_APP_ID"
    - "FIREBASE_MESUREMENT_ID"="$_FIREBASE_MESUREMENT_ID"
    - "IDENTITY_SERVICE_URL="$_IDENTITY_SERVICE_URL"



steps:
  #コンテナイメージをビルドする
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t=gcr.io/$PROJECT_ID/harumax-identity-service', '.']
  #コンテナイメージをpushする
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/harumax-identity-service"]
  #もろもろの設定
  - name: "gcr.io/cloud-builders/gcloud"
  - serviceAccount: "projects/$PROJECT_ID/serviceAccounts/harumax-identity-service@harumax.iam.gserviceaccount.com"
    args:
      - "alpha"
      - "run"
      - "deploy"
      - "harumax-identity-service"
      - "--image=gcr.io/$PROJECT_ID/harumax-identity-service"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
