FROM node:16 AS builder

WORKDIR /app

COPY package*.json ./
ENV PORT=8080

ARG _HTML_NAME
ENV HTML_NAME ${_HTML_NAME}}
ARG _BASE_DOMAIN
ENV BASE_DOMAIN ${_BASE_DOMAIN}

ARG _FIREBASE_API_KEY
ENV FIREBASE_API_KEY ${_FIREBASE_API_KEY}
ARG _FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN ${_FIREBASE_AUTH_DOMAIN}
ARG _FIREBASE_DATABASE_URL
ENV FIREBASE_DATABASE_URL ${_FIREBASE_DATABASE_URL}
ARG _FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID ${_FIREBASE_PROJECT_ID}
ARG _FIREBASE_STORAGE_BUCKET
ENV FIREBASE_STORAGE_BUCKET ${_FIREBASE_STORAGE_BUCKET}
ARG _FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_MESSAGING_SENDER_ID ${_FIREBASE_MESSAGING_SENDER_ID}
ARG _FIREBASE_APP_ID
ENV FIREBASE_APP_ID ${_FIREBASE_APP_ID}
ARG _FIREBASE_MESUREMENT_ID
ENV FIREBASE_MESUREMENT_ID ${_FIREBASE_MESUREMENT_ID}
ARG _IDENTITY_SERVICE_URL
ENV IDENTITY_SERVICE_URL ${_IDENTITY_SERVICE_URL}
ARG _SA_KEY
ENV SA_KEY ${_SA_KEY}
ARG _SA_KEY_ID
ENV SA_KEY_ID ${_SA_KEY_ID}
ARG _SA_NAME
ENV SA_NAME ${_SA_NAME}}


RUN npm install

COPY ./ ./

RUN npm run build

CMD ["npm", "run", "start:prod"]
